version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
    volumes:
      - .:/app
    command: waitress-serve --host=0.0.0.0 --port=5000 app:app

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
